services:
  api:
    build: ./server        
    ports:
      - "3001:3001"
    volumes:
      - ./server:/server
    command: bash -c "node server.js"

  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend